### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ChillarAnand** [mikelhernaez/qvz#2]
I am trying to run qvz and it is throwing segmenation fault. Not sure how to debug.

I am using Linux.

```
 3.13.0-65-generic #105~precise1-Ubuntu SMP Tue Sep 22 13:22:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gmalysa** [comment]
Hi @ChillarAnand,

Do you have a link to a copy of the file you are trying to compress? Or some details about it (phred offset, alphabet size, etc.) Some of these things are hardcoded (unfortunately) due to the development time we had. A minimal version of the file-to-compress that can reproduce the errors would be very helpful.

**Comment by ChillarAnand** [comment]
I was able to reproduce it with small data set, sent that file to your personal mail @gmalysa

**Comment by gmalysa** [comment]
Thanks, got it!

qvz only compresses the quality scores within a fastq file; the reads and other data must be encoded separately. They are compressed in order so that you can re-combine them to create a fastq after decompression. Using this command line to pull out the quality scores only and then compress them ran ok for me:

$ sed -n '0~4p' 10.fastq > 10.quality_only
$ bin/qvz -s 10.quality_only 10.qvz
rate, 0.6947, distortion, 11.3842, time, 0.1000, size, 33 

Please let me know if this works for you as well or if there are other issues!

**Comment by ChillarAnand** [comment]
:+1:  Thanks :)
